spring:
  data:
    mongodb:
      username: mongouser
      password: mongopassword
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin
  kafka:
    consumer:
      bootstrap-server: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringSerializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.ecomm.order.kafka.OrderConfirmation,paymentConfirmation:com.ecomm.payment.notification.PaymentNotificationRequest


  mail:
    host: localhost
    port: 1025
    username: alibou
    password: alibou
    properties:
      mail:
        trust: "*"
        auth: true
        starttls:
          enabled: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000



server:
  port: 8040